cart/urls.py
from django.urls import path
from cart import views

urlpatterns = [
    path('ver-carrito/', views.cart_page_detail, name='cart_page_detail'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # Django Tradicional
    path('', include("home.urls")),
    path('', include("home.urls_api")),
    path('', include("users.urls")),
    
    path('', include("cart.urls")),
    path('', include("products.urls")),
    path('', include("dashboard.urls")),
    path('', include("profiles.urls")),
    path('', include("favorites.urls")),
    
    path('', include("orders.urls")),
    path('', include("payments.urls")),
    path('', include("contact.urls")),
    
    # DRF API
    path('', include("users.urls_api")),
    
    path('', include("cart.urls_api")),
    path('', include("products.urls_api")),
    path('', include("orders.urls_api")),
]


# eliminar en producion
from django.conf import settings

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

profiles/urls.py
from django.urls import path
from profiles import views


urlpatterns = [
    
    path('perfil/', views.profile_page, name='profile_user'),
    path('profile/tab/<str:tab_name>/', views.profile_tabs, name='profile_tabs'),
]

users/urls.py
from django.urls import path
from users import views


urlpatterns = [
    path('register-user/', views.register_user, name='register_user_page'),
]

users/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import BaseUserManager


# Custom User Manager responsible for creating users and superusers
class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        # Raise an error if no email is provided
        if not email:
            raise ValueError('The Email field must be set')
        
        # Normalize the email to ensure correct format
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        # Set the encrypted password
        user.set_password(password)
        # Save the user to the database
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        # Ensure that superusers have specific permissions
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        # Call the regular user creation for the superuser
        return self.create_user(email, password, **extra_fields)


# Modelo de usuario personalizado que reemplaza al modelo por defecto de Django
class CustomUser(AbstractUser):
    # Remove the 'username' field from the default model
    username = None 

    email = models.EmailField(unique=True)  # The email field must be unique for each user
    cellphone = models.CharField(max_length=20, blank=True, null=True)  # Phone number (optional)
    province = models.CharField(max_length=50, blank=True, null=True)  # User's province (optional)
    address = models.CharField(max_length=255, blank=True, null=True)  # User's address (optional)

    ROLE_CHOICES = [
        ('admin', 'Admin'),
        ('seller', 'Vendedor'),
        ('buyer', 'Comprador'),
    ]
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='buyer')

    """ 
    Other fields:
    first_name: User's first name.
    last_name: User's last name.
    is_active: Boolean indicating if the user is active.
    is_staff: Boolean indicating if the user has admin privileges.
    is_superuser: Boolean indicating if the user is a superuser.
    last_login: Date and time of the user's last login.
    date_joined: Date and time when the user registered.
    groups: Groups the user belongs to.
    user_permissions: Specific permissions assigned to the user.
    """

    # Use email instead of 'username' for authentication
    USERNAME_FIELD = "email"

    # No additional fields are required to create a superuser (by default only email and password are needed)
    REQUIRED_FIELDS = []  # If you add extra fields, list them here

    # Assign the CustomUserManager to handle user creation
    objects = CustomUserManager()

    # Method to represent the user as a string (using email)
    def __str__(self):
        return self.email  # Returns the email address as the user's string representation

profiles/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse

from profiles import utils_tabs


# Create your views here.
def profile_page(request):
    user = request.user
    
    if not user.is_authenticated:
        return redirect('/')

    # Verificar si es admin o superadmin
    if user.id == 1 or user.role == 'admin':
        return render(request, 'profiles/admin/adm_profile.html')

    # User Profile Comun
    return render(request, 'profiles/user/user_profile.html')


def profile_tabs(request, tab_name):
    """ 
        cada condicion devuelve de forma asincrona mediante un fetch el html renderizado ademas de un javascript
        asociado para poder utilizar en la pagina
    """
    user = request.user
    if not user.is_authenticated:
        # capaz ver de redirigir al home..
        return JsonResponse({'detail': 'No estás registrado..'}, status=404)
    
    if user.role == 'buyer':
        response = utils_tabs.profile_tabs_user(user, tab_name)
        if response:
            return JsonResponse(response, status=200)
    
    elif user.role == 'admin':
        response = utils_tabs.profile_tabs_admin(request, tab_name)
        if response:
            return JsonResponse(response, status=200)
        
    return JsonResponse({'detail': 'Tab not found.'}, status=404)

users/views.py
# Create your views here.
from django.shortcuts import render


def register_user(request):
    from users.choices import PROVINCIAS_CHOICES
    context = {'provinces': PROVINCIAS_CHOICES}
    return render(request, 'users/register_user.html', context)

users/templates/users/admin_profile.html
{% extends "home/base.html" %}

{% load static %}
{% load custom_filters %}

<!-- For More CSS Modules -->
{% block extra_head %}

    <title> Admin | {{ user.first_name }} {{ user.last_name }}</title>

    <link href="{% static 'users/css/admin_profile.css' %}" rel="stylesheet">

{% endblock extra_head %}


<!-- Contenido principal de la pagina -->
{% block main_content %}

<div class="d-grid cont-grid-11-13">

    <!-- tarjeta del usuario e INFO CONTACTO -->
    <aside class="d-flex-col gap-2">

        <!-- Columna perfil + botones edit y logout -->
        <div class="border-hover bg-primary d-flex-col w-100 align-center gap-1 p-3">

            <img src="https://i.pinimg.com/736x/80/8d/03/808d03843400c4392b7891c1a6428104.jpg" 
            class="img-circle" alt="User Image Profile">
            
            <span class="mt-1"><b>{{ user.first_name }} {{user.last_name}}</b></span>
            <span> {{ user.email }} </span>
            <span> <b class="bold-green">Rol:</b> <b class="bold-main text-capitalize">{{ user.role }} </b></span>
        
            <!-- 		
            <a href="#" class="btn btn-main w-100 btn-36">
                <b>Premium Account</b>
            </a> -->

            <a href="{% url 'main_dashboard' %}" class="btn btn-40 w-100 gap-1 btn-main">
                <i class="ri-dashboard-horizontal-line font-xl"></i>
                <strong class="text-md">Panel de control</strong>
            </a>

            <!-- BOTONES EDITAR Y LOGEARSE -->
            <div class="d-flex-col mt-1 w-100">
                <button class="btn gap-1 btn-secondary border-secondary p-border-top btn-36 w-100">
                    <p class="font-sm"><b>Editar Datos</b></p>
                    <i class="ri-settings-4-line font-lg"></i>
                </button>
            
                <form class="form-close-profile" method="POST" action="{% url 'close_session' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn gap-1 btn-secondary border-secondary p-border-bot btn-36 w-100">
                        <i class="ri-door-open-fill font-lg"></i>
                        <span class="font-md">Cerrar Sesión</span>
                    </button>
                </form>
            </div>
        </div>
        
        <!-- Tarjeta Info Contacto -->
        <div class="border-hover bg-primary d-flex-col w-100 align-start gap-2 p-3 d-desktop-flex">
            <p class="bold-main">Datos Tienda</p>

            <div class="d-flex-col w-100">
                <div class="d-flex gap-1 border-secondary p-border-top btn-36 w-100 not-border-bottom">
                    <i class="ri-mail-line font-lg ms-2"></i>
                    <span class="text-truncate">{{ store.email|default:"No hay E-mail." }}</span>
                </div>
    
                <div class="d-flex gap-1 border-secondary btn-36 w-100">
                    <i class="ri-phone-line font-lg ms-2"></i>
                    <span>
                        {% if store.cellphone %} +54 9 {{ store.cellphone }}
                        {% else %} No hay número.
                        {% endif %}
                    </span>
                </div>
    
                <div class="d-flex gap-1 border-secondary p-border-bot btn-36 w-100">
                    <i class="ri-home-4-line font-lg ms-2"></i>
                    <span>{{ store.address|default:"No hay dirección." }}</span>
                </div>
            </div>
        </div>
    </aside>

    <!-- CONTENIDO del perfil -->
    <div class="border-secondary">
        <!-- BANNER -->
        <div class="cont-banner-profile">
            <img src="https://i.pinimg.com/736x/3b/da/58/3bda585ceabcae86a826c57305d1ff39.jpg" 
                class=" img-cover" alt="BANNER PROFILE">
        </div>

        <!-- ITEMS BANNER -->
        <div class="d-grid w-100 cont-tabs">
            <button class="active btn btn-alt gap-1 btn-40 w-100 btn-tabs" data-tab="first-tab">
                <!-- 		 <a class="gap-2 text-white" data-content="First Tab">  </a>-->
                <i class="ri-time-line font-lg"></i>
                <p class="font-md"><b>Pedidos Pendientes</b></p>
            </button>

            <button class="btn btn-alt gap-1 white-border-right-left btn-40 w-100 btn-tabs" data-tab="users-tab">
                <!-- 		 <a class="gap-2 text-white" data-content="First Tab">  </a>-->
                <i class="ri-heart-line font-lg"></i> 
                <p class="font-md"><b>Usuarios</b></p>   
            </button>

            <button class="btn btn-alt gap-1 btn-40 w-100 btn-tabs" data-tab="store-data-tab">
                <!-- 		 <a class="gap-2 text-white" data-content="First Tab">  </a>-->
                <i class="ri-store-2-line font-lg"></i> 
                <p class="font-md"><b>Datos Tienda</b></p>   
            </button>
        </div>

        <!-- DASHBOARD HEADERS Y BANNERS { % include "users/tabs/admin_headers.html" % }-->
        <div class="tab-content p-2" id="first-tab"></div>

        <!-- DASHBOARD STORE DATA  { % include "users/tabs/admin_store.html" % }-->
        

        <div class="tab-content p-2" id="users-tab"></div>

        <div class="tab-content p-2" id="store-data-tab"></div>
    </div>

</div>

{% endblock main_content %}


{% block extra_scripts %}

    <!-- JavaScript for Product Page -->
    <script>
        window.TEMPLATE_URLS = {
            // users/urls.py
            profileTabs: "{% url 'profile_tabs' 0 %}".replace('0/', '{tab_name}/'),

            // home/urls.py
            storeUpdate: "{% url 'update_store' 0 %}".replace('0/', '{store_id}/'),

            // payments/urls.py
            shipmentUpdate: "{% url 'update_shipment' 0 %}".replace('0/', '{shipment_id}/'),
            paymentUpdate: "{% url 'update_payment' 0 %}".replace('0/', '{payment_id}/'),

            // users
            userRoleUpdate: "{% url 'user_edit_role' 0 %}".replace('0/', '{user_id}/')
        };
    </script>

    <script src="{% static 'users/js/admin_profile.js' %}"></script>

{% endblock extra_scripts %}

users/templates/users/profile.html
{% extends "home/base.html" %}

{% load static %}

<!-- For More CSS Modules -->
{% block extra_head %}

    <title> Profile | {{ user.first_name }} {{ user.last_name }}</title>

    <!-- Swiper CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.css">
    
    
    <link href="{% static 'products/css/products_carousel.css' %}" rel="stylesheet">
    <link href="{% static 'products/css/products_cards.css' %}" rel="stylesheet">

    <link href="{% static 'users/css/profile.css' %}" rel="stylesheet">

{% endblock extra_head %}


<!-- Contenido principal de la pagina -->
{% block main_content %}

<div class="d-grid cont-grid-11-13">

    <!-- tarjeta del usuario e INFO CONTACTO -->
    <aside class="d-flex-col gap-2">

        <!-- Columna perfil + botones edit y logout -->
        <div class="border-hover bg-primary d-flex-col w-100 align-center gap-1 p-3">

            <img src="https://i.pinimg.com/736x/80/8d/03/808d03843400c4392b7891c1a6428104.jpg" 
            class="img-circle" alt="User Image Profile">
            
            <span class="mt-1"><b>{{ user.first_name }} {{user.last_name}}</b></span>
            <span> {{ user.email }} </span>
        
            <!-- 		
            <a href="#" class="btn btn-main w-100 btn-36">
                <b>Premium Account</b>
            </a> -->

            <!-- BOTONES EDITAR Y LOGEARSE -->
            <div class="d-flex-col mt-1 w-100">
                <button class="btn gap-1 btn-secondary border-secondary p-border-top btn-36 w-100">
                    <p class="font-sm"><b>Editar Datos</b></p>
                    <i class="ri-settings-4-line font-lg"></i>
                </button>
            
                <form class="form-close-profile" method="POST" action="{% url 'close_session' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn gap-1 btn-secondary border-secondary p-border-bot btn-36 w-100">
                        <i class="ri-door-open-fill font-lg"></i>
                        <span class="font-md">Cerrar Sesión</span>
                    </button>
                </form>
            </div>
        </div>
        
        <!-- Tarjeta Info Contacto -->
        <div class="border-hover bg-primary d-flex-col w-100 align-start gap-2 p-3 d-desktop-flex">
            <p class="bold-main">Contacto</p>

            <div class="d-flex-col w-100">
                <div class="d-flex gap-1 border-secondary p-border-top btn-36 w-100 not-border-bottom">
                    <i class="ri-mail-line font-lg ms-2"></i>
                    <span class="text-truncate">{{ user.email|default:"No hay E-mail." }}</span>
                </div>
    
                <div class="d-flex gap-1 border-secondary btn-36 w-100">
                    <i class="ri-phone-line font-lg ms-2"></i>
                    <span>
                        {% if user.phone %} +54 9 {{ user.phone }}
                        {% else %} No hay número.
                        {% endif %}
                    </span>
                </div>
    
                <div class="d-flex gap-1 border-secondary p-border-bot btn-36 w-100">
                    <i class="ri-home-4-line font-lg ms-2"></i>
                    <span>{{ user.address|default:"No hay dirección." }}</span>
                </div>
            </div>
        </div>
    </aside>

    <!-- CONTENIDO del perfil -->
    <div class="border-secondary">
        <!-- BANNER -->
        <div class="cont-banner-profile">
            <img src="https://i.pinimg.com/736x/3b/da/58/3bda585ceabcae86a826c57305d1ff39.jpg" 
                class=" img-cover" alt="BANNER PROFILE">
        </div>

        <!-- ITEMS BANNER -->
        <div class="d-grid w-100 cont-tabs">
            <button class="active btn btn-alt gap-1 btn-40 w-100 btn-tabs" data-tab="first-tab">
                <!-- 		 <a class="gap-2 text-white" data-content="First Tab">  </a>-->
                <i class="ri-time-line font-lg"></i>
                <p class="font-md"><b>Pedidos Pendientes</b></p>
            </button>

            <button class="btn btn-alt gap-1 white-border-right-left btn-40 w-100 btn-tabs" data-tab="favorites-tab">
                <!-- 		 <a class="gap-2 text-white" data-content="First Tab">  </a>-->
                <i class="ri-heart-line font-lg"></i> 
                <p class="font-md"><b>Productos Favoritos</b></p>   
            </button>

            <button class="btn btn-alt gap-1 btn-40 w-100 btn-tabs" data-tab="third-tab">
                <!-- 		 <a class="gap-2 text-white" data-content="First Tab">  </a>-->
                <i class="ri-store-2-line font-lg"></i> 
                <p class="font-md"><b>Mis Compras</b></p>   
            </button>
        </div>

        <!-- DASHBOARD PRODUCTOS -->
        <div class="tab-content p-2" id="first-tab"></div>

        <div class="tab-content p-2" id="favorites-tab"></div>

        <div class="tab-content p-2" id="third-tab"></div>
    </div>

</div>

{% endblock main_content %}


{% block extra_scripts %}

    <!-- JavaScript for Product Page -->
    <script>
        window.TEMPLATE_URLS = {
            // users/urls.py
            profileTabs: "{% url 'profile_tabs' 0 %}".replace('0/', '{tab_name}/'),

            // favorites/urls.py
            favorites: "{% url 'toggle-favorite' 0 %}".replace('0/', '{product_id}/'),
            
            // products/urls.py
            addToCart: "{% url 'cart_add_product' %}",
            productDetail: "{% url 'product_detail' id=0 slug='__SLUG__' %}",
            category: "{% url 'pl_category' cat_slug='__CAT__' %}",
            subcategory: "{% url 'pl_subcategory' cat_slug='__CAT__' subcat_slug='__SUBCAT__' %}",
            brand: "{% url 'pl_brand' brand_slug='__BRAND__' %}"
        };
    </script>

    <!-- Swiper JS sirve para el carousel -->
    <script src="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js"></script>

    <script src="{% static 'products/js/products_cards.js' %}"></script>

    <script src="{% static 'products/js/products_carousel.js' %}"></script>

    <script src="{% static 'users/js/profile.js' %}"></script>
{% endblock extra_scripts %}

users/templates/users/register_user.html
{% extends "home/base.html" %}
{% load static compress %}


{% block extra_head %}
    {% compress css %}
        <link rel="stylesheet" href="{% static 'users/css/register_user.css' %}">
    {% endcompress %}
{% endblock %}
    

{% block main_content %}
    <div class="d-flex mb-2 gap-1">
        <a class="btn btn-parallelogram" href="{% url 'Home' %}">
            <span class="font-md px-1">Home</span>
        </a>

        <button class="btn btn-parallelogram px-1">
            <span class="font-md px-1">Registro</span>
        </button>
    </div>

    <div class="d-grid cont-grid-11-13 gap-2">
        {# Primera Fila #}
        <div class="d-flex-col gap-2 bg-primary border-hover h-min p-2">
            <h2 class="text-start">Registrarse</h2>
            <p class="text-start">
                Puedes registrarte como un usuario del sitio, podras gestionar tus compras, 
                consultas y datos personales.
            </p>
            {# este mensaje es para cuando quieren continuar con la compra sin cuenta #}
            {% if flag_to_login %}		
                <span class="p-1 border-hover border-main text-start bolder">
                    Por favor para continuar con su compra debe registrarse con una cuenta, 
                    o puede logearse si asi lo desea.
                </span>
            {% endif %}
        </div>

        {# Segunda Fila #}
        <form class="d-grid cont-grid-122 gap-2 h-min bg-primary border-hover p-3" id="register-form">
            {% csrf_token %}
            
            {# Fila para Email y Password #}
            <label class="d-flex-col gap-1 bolder">
                E-mail
                <input type="email" name="email" required>
            </label>

            <label class="d-flex-col gap-1 bolder">
                Password
                <input type="password" name="password" required>
            </label>

            {# Fila para Nombre y Apellido #}
            <label class="d-flex-col gap-1 bolder">
                Nombre
                <input type="text" name="first_name" required>
            </label>

            <label class="d-flex-col gap-1 bolder">
                Apellido
                <input type="text" name="last_name" required>
            </label>

            {# Fila para Teléfono y Provincia #}
            <label class="d-flex-col gap-1 bolder">
                Celular
                <input type="text" name="cellphone" required>
            </label>

            <label class="d-flex-col gap-1 bolder">
                Provincia
                <select name="province" id="id_province">
                    {% for key, value in provinces %}
                        <option value="{{ key }}">{{ value }}</option>
                    {% endfor %}
                </select>
            </label>

            {# Fila para Dirección #}
            <label class="d-flex-col gap-1 bolder address-label grid-col-all">
                Dirección
                <input type="text" name="address" required>
            </label>

            {# buttons form #}
            <div class="mt-2 grid-col-all d-flex gap-2">
                <button class="btn btn-32 w-50 p-2 btn-main font-md bolder" type="submit"
                data-action="Register" data-url="{% url 'register_user' %}">
                    Crear
                </button>

                <button class="btn btn-32 w-50 py-1 px-2 btn-alt" id="have-account" type="button">
                    <span class="text-truncate font-md bolder">Ya tengo cuenta</span>
                </button>
            </div>
        </form>
    </div>
{% endblock %}


{% block extra_scripts %}
    {% compress js %}
        <script src="{% static 'users/js/register_user.js' %}"></script>
    {% endcompress %}
{% endblock extra_scripts %}

users/templates/users/widget_login.html
{# Contenido del dropdown #}
<form class="user-dropdown d-flex-col gap-1 border-main form-user-dropdown" data-state="null">
    {% csrf_token %}

    {% if user.is_authenticated %}
        {# Botón de Perfil #}
        <a href="{% url 'profile_user' %}" class="btn btn-main btn-36 w-100 gap-1">
            <i class="ri-shield-user-line font-xl"></i>
            <span class="text-truncate font-md bolder"> {{ user.email }} </span>
        </a>

        <button type="submit" class="btn btn-alt btn-36 w-100 gap-1 font-md bolder"
        data-url="{% url 'close_session' %}" data-action="Close">
            <i class="ri-door-open-fill font-lg fw-normal"></i>
            Cerrar Sesión
        </button>
        
    {% else %}
        {# Cuando el usuario no esta logeado verá esto #}
        <label class="d-flex-col gap-1 text-start font-md bolder">
            Email:
            <input class="btn-36 w-100" type="email" name="email" required>
        </label>
    
        <label class="d-flex-col gap-1 text-start font-md bolder">
            Password:
            <input class="btn-36 w-100" type="password" name="password" required>
        </label>
    
        {# Botón de Login #}
        <button type="submit" class="btn btn-main btn-36 w-100 mt-1 bolder font-md"
        data-url="{% url 'widget_login' %}" data-action="Login">
            Ingresar
        </button>
            
        {# Botón de Registro #}
        <a href="{% url 'register_user_page' %}" class="btn btn-alt btn-36 w-100 mt-1 font-md bolder">
            Registrarse
        </a>
    {% endif %}
</form>